roles limitations
Pepperi-Addons/core-generic-resources pull request #140
Opened 2024-04-17 09:08 UTC by leonPep42

2024-04-17 09:57 UTC, saargt requested changes

2024-04-17 09:57 UTC, saargt commented on server-side/services/limitations.service.ts
> +		const relation = varSettingsRelation;
Make a shallow copy of the varSettingsRelation, otherwise you're changing a global const - the next run the Lambda has of Core Resources (could be of another dist!) will have this relation with Hidden=hidden, which might cause a really hard to find bug.

2024-04-17 09:57 UTC, saargt commented on server-side/services/limitations.service.ts
> +		if (parseInt(varSettings.Depth) > 10)
Extract hard limits and default soft limits to readonly consts.

2024-04-17 09:57 UTC, saargt commented on server-side/services/limitations.service.ts
> +		// TODO: use kms api when it's ready
❤️

2024-04-17 09:57 UTC, saargt commented on server-side/services/limitations.service.ts
> +		if (parseInt(varSettings.Count) > 250)
I think you must validate the current Count and Depth before setting the new value.
Say, if there are 100 roles, and support sets the limit to 90, now the dist will not be able to edit existing roles.

2024-04-17 09:57 UTC, saargt commented on server-side/services/limitations.service.ts
> +			const parentRole = roles.find(r => r.InternalID === parent);
This might be expensive.
I think you can populate some more suitable data structure to quickly get the parent, perhaps a dictionary from InternalID -> role

2024-04-21 09:50 UTC, leonPep42 commented on server-side/services/limitations.service.ts
> +			const parentRole = roles.find(r => r.InternalID === parent);
maximum depth is 10, so it's not really a loop

2024-04-22 06:44 UTC, saargt approved these changes

2024-04-22 07:09 UTC, merged