Di 23260
Pepperi-Addons/core-generic-resources pull request #31
Opened 2023-03-16 12:36 UTC by leonPep42

2023-03-19 13:46 UTC, ShirMarciano commented on server-side/services/pns.service.ts
> +        this.requestedUserFields = "UUID,FirstName,LastName,Name,Email,InternalID,ExternalID,Mobile";
Why the fields are hard coded? and nor from the schema?

2023-03-19 13:48 UTC, ShirMarciano commented on server-side/services/pns.service.ts
> +        const coreAddonUUID = "00000000-0000-0000-0000-00000000c07e";
This should be one function that will be called separately for each resource instead of the code duplication

2023-03-19 14:03 UTC, ShirMarciano commented on server-side/services/pns.service.ts
> +
Both function have code duplication- all the part of getting the objects that was changed from papi is the same.
Consider do BasePNSService אhat usersPNSService and accountUsersPNSService (I know that it isnt in this pull request yet ) will inherit from

2023-03-19 14:05 UTC, ShirMarciano requested changes
General comment - all functions are missing return type

2023-03-20 11:16 UTC, saargt requested changes

2023-03-20 11:16 UTC, saargt commented on server-side/services/pns.service.ts
> +            if(contact.IsBuyer==false && contactsContainedInUsers.Objects.find(user => user.Key==contact.Key)) {
!contact.IsBuyer

2023-03-20 11:16 UTC, saargt commented on server-side/services/pns.service.ts
> +            } else if(contact.IsBuyer==true) {
contact.IsBuyer

2023-03-20 11:16 UTC, saargt commented on server-side/services/pns.service.ts
> +        papiUpdatedContacts.forEach(async contact => {
Using foreach and promises is tricky... Will this work as you intend?
If the POSTs to hard_delete users are done latrew on the event loop, the Lambda might die after the function is over, without sending all the requests.

2023-03-20 11:16 UTC, saargt commented on server-side/services/resourceHelper.service.ts
> +        this.papiClient = new PapiClient({
See papiClient comment from pns.service.ts

2023-03-20 11:16 UTC, saargt commented on server-side/services/resourceHelper.service.ts
> +    constructor(private client: Client) {
See client property comment in pns.service.ts

2023-03-20 11:16 UTC, saargt commented on server-side/adal.ts
> +    const service = new PNSService(client);
I like to create objects only after the validations, so we don't do extra work, consuming more memory and time for a request that is about to fail.
Try moving the instantiation into the if-true

2023-03-20 11:16 UTC, saargt commented on server-side/services/pns.service.ts
> +        const usersUUIDs = messageFromPNS.FilterAttributes.ModifiedObjects;
I think PNS messages might get really big, and fail to get logged on cloudwatch. It might not be a good idea to print the entire message, perhaps filter out only the data that is meaningful in a debugging scenario.

2023-03-21 10:23 UTC, ShirMarciano commented on server-side/services/pns.service.ts
> +        const usersUUIDs = messageFromPNS.FilterAttributes.ModifiedObjects;
@leonPep42 Do you get an actionUUID on the messageFromPNS?

2023-03-21 13:27 UTC, saargt requested changes
Please run 'npm run lint' from root folder.

2023-03-21 13:27 UTC, saargt commented on server-side/services/resourceHelper.service.ts
> +    replaceUUIDWithKey(user) {
This function both modifies the passed paramter, and returns it.
A caller might not expect this to happen. Either make a deep copy and return it, or return void and modify the parameter.

2023-04-17 08:20 UTC, ShirMarciano commented
Not relevant pull request - there is a new design that will be in other PR

2023-04-17 08:20 UTC, closed without merging