Di 23270
Pepperi-Addons/core-generic-resources pull request #38
Opened 2023-04-04 06:48 UTC by leonPep42

2023-04-13 08:57 UTC, saargt reviewed
Please add modifiers to methods.

2023-04-13 08:57 UTC, saargt commented on server-side/adal.ts
> +	const papiClient = Helper.getPapiClient(client);
Please move instantiations into to the if-true scopes.

2023-04-13 08:57 UTC, saargt commented on server-side/services/builders/build.service.ts
> +    async buildAdalTableHelper(adalTable: string, body: any, where = ""): Promise<any>
buildAdalTableHelper() and abstract buildAdalTable() have the same relationship we discussed in basePNS. buildAdalTableHelper() implementation should call the abstract buildAdalTable which should provice the actual data for the table building.
This will also allow you to give better names than buildAdalTableHelper and buildAdalTable. Maybe something like buildAdalTableHelper -> buildAdalTable and buildAdalTable -> getTableBuildParams.

2023-04-13 08:57 UTC, saargt commented on server-side/services/adalHelper.service.ts
> +	async batchUpsert(objects: any[], resource: string)
Can't batchUpsert() and getByKeys() be move into the Getter class (Now we can name it PapiService or something)? That way you make the AdalHelperClass have a meaningful purpose - it is the build manager or build executioner. Now it can have a good name, and the PapiService would have all papi related functionality. All classes that inherit from BasePns won't need to have an AdalHelperService instance.

2023-04-13 08:57 UTC, saargt commented on server-side/services/builders/build.service.ts
> +		this.papiClient = papiClient;
Why is papiClient a memeber of this class?

2023-04-24 13:07 UTC, saargt requested changes

2023-04-24 13:07 UTC, saargt commented on server-side/services/getters/papiGetter.service.ts
> +	async getRequestedFieldsString(): Promise<string>
Please add modifiers to your methods - public, protected, private.

2023-04-24 13:07 UTC, saargt commented on server-side/services/pns/basePNS.service.ts
> +	constructor(papiClient: PapiClient)
All the classes the inherit from this class have 'protected adalService: AdalService'. Why not move it here, and get it in the 'ctor?

2023-04-24 14:26 UTC, leonPep42 commented on server-side/services/pns/basePNS.service.ts
> +	constructor(papiClient: PapiClient)
We said that we should not force services who inherits from basePNS service to provide adalService because the base service doesn't use it, am I wrong?

2023-04-27 07:16 UTC, saargt approved these changes

2023-04-27 12:53 UTC, merged